apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  params:
  - name: username
    type: string
  steps:
    - name: goodbye
      image: gcr.io/distroless/base-debian12:debug-nonroot@sha256:dcc1690cf35ecb2cc4869ed45494d0d6ca58a66b989810e67abe0d405b23eb9c
      script:
        #!/bin/bash
        echo "Goodbye $(params.username)!"
        echo "Final test123"
